FloatLayout:
    MDLabel:
        text: "First label"
        halign: "center"
        pos_hint: {"center_x": 0.5, "center_y": 0.5}
    
    BoxLayout:
        orientation: "horizontal"
        size_hint: 1, 0.2
        pos_hint: {"x": 0, "y": 0}

        MDRectangleFlatButton:
            text: "Button 1"

        MDRectangleFlatButton:
            text: "Button 2"

        MDRectangleFlatButton:
            text: "Button 3"